# Generated by Django 3.1.4 on 2021-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Соглашение на отправку уведомлений на почту'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Мужской пол'), ('Woman', 'Женский пол')], default='Man', max_length=11, verbose_name='Выбор пола'),
        ),
    ]
